//------------------------------------------------------------------------------
// <auto-generated>
//     此代码自动生成
//	   生成时间 2019-03-05 10:35:22 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using QSDMS.Data.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace Sys.Data.IServices
{
    /// <summary>
    /// 接口类：ISettingsService 
    /// </summary>
  
    public interface  ISettingsService<T, Q, P> : IDAL<T, Q, P>
    {  
		
    }    
}
	