//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：CategoryEntity 
    /// </summary>
    [Serializable()]
    public partial class CategoryEntity:BaseModel
    {  
		            
		/// <summary>
		/// CategoryID:string
		/// </summary>	
		public string CategoryID { get; set; }
                    
		/// <summary>
		/// Name:string
		/// </summary>	
		public string Name { get; set; }
                    
		/// <summary>
		/// Code:string
		/// </summary>	
		public string Code { get; set; }
                    
		/// <summary>
		/// ParentID:string
		/// </summary>	
		public string ParentID { get; set; }
                    
		/// <summary>
		/// CategoryPath:string
		/// </summary>	
		public string CategoryPath { get; set; }
                    
		/// <summary>
		/// Depth:byte
		/// </summary>	
		public byte? Depth { get; set; }
                    
		/// <summary>
		/// SortNum:int
		/// </summary>	
		public int? SortNum { get; set; }
                    
		/// <summary>
		/// ImagePath:string
		/// </summary>	
		public string ImagePath { get; set; }
                    
		/// <summary>
		/// IsHidden:byte
		/// </summary>	
		public byte? IsHidden { get; set; }
           
    }    
}
	