//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：DeliverOrderEntity 
    /// </summary>
    [Serializable()]
    public partial class DeliverOrderEntity:BaseModel
    {  
		            
		/// <summary>
		/// DeliverOrderId:string
		/// </summary>	
		public string DeliverOrderId { get; set; }
                    
		/// <summary>
		/// OrderId:string
		/// </summary>	
		public string OrderId { get; set; }
                    
		/// <summary>
		/// OrderStatus:int
		/// </summary>	
		public int? OrderStatus { get; set; }
                    
		/// <summary>
		/// Freight:decimal
		/// </summary>	
		public decimal? Freight { get; set; }
                    
		/// <summary>
		/// AddressId:string
		/// </summary>	
		public string AddressId { get; set; }
                    
		/// <summary>
		/// MemberId:string
		/// </summary>	
		public string MemberId { get; set; }
                    
		/// <summary>
		/// MemberName:string
		/// </summary>	
		public string MemberName { get; set; }
                    
		/// <summary>
		/// MemberMobile:string
		/// </summary>	
		public string MemberMobile { get; set; }
                    
		/// <summary>
		/// LogisticsNo:string
		/// </summary>	
		public string LogisticsNo { get; set; }
                    
		/// <summary>
		/// LogisticsName:string
		/// </summary>	
		public string LogisticsName { get; set; }
                    
		/// <summary>
		/// LogisticsCode:string
		/// </summary>	
		public string LogisticsCode { get; set; }
                    
		/// <summary>
		/// LogisticsTime:DateTime
		/// </summary>	
		public DateTime? LogisticsTime { get; set; }
                    
		/// <summary>
		/// BillCode:string
		/// </summary>	
		public string BillCode { get; set; }
                    
		/// <summary>
		/// CreateDate:DateTime
		/// </summary>	
		public DateTime? CreateDate { get; set; }
                    
		/// <summary>
		/// Remark:string
		/// </summary>	
		public string Remark { get; set; }
                    
		/// <summary>
		/// SaleOrderNo:string
		/// </summary>	
		public string SaleOrderNo { get; set; }
                    
		/// <summary>
		/// ProCount:int
		/// </summary>	
		public int? ProCount { get; set; }
                    
		/// <summary>
		/// YunFee:decimal
		/// </summary>	
		public decimal? YunFee { get; set; }
           
    }    
}
	