//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：LogistCompEntity 
    /// </summary>
    [Serializable()]
    public partial class LogistCompEntity:BaseModel
    {  
		            
		/// <summary>
		/// LogistCompId:string
		/// </summary>	
		public string LogistCompId { get; set; }
                    
		/// <summary>
		/// LogistCompCode:string
		/// </summary>	
		public string LogistCompCode { get; set; }
                    
		/// <summary>
		/// LogistCompName:string
		/// </summary>	
		public string LogistCompName { get; set; }
                    
		/// <summary>
		/// SortNum:int
		/// </summary>	
		public int? SortNum { get; set; }
                    
		/// <summary>
		/// Remark:string
		/// </summary>	
		public string Remark { get; set; }
           
    }    
}
	