//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：MemberEntity 
    /// </summary>
    [Serializable()]
    public partial class MemberEntity:BaseModel
    {  
		            
		/// <summary>
		/// MemberId:string
		/// </summary>	
		public string MemberId { get; set; }
                    
		/// <summary>
		/// MemberName:string
		/// </summary>	
		public string MemberName { get; set; }
                    
		/// <summary>
		/// Mobile:string
		/// </summary>	
		public string Mobile { get; set; }
                    
		/// <summary>
		/// Sex:int
		/// </summary>	
		public int? Sex { get; set; }
                    
		/// <summary>
		/// CreateTime:DateTime
		/// </summary>	
		public DateTime? CreateTime { get; set; }
                    
		/// <summary>
		/// BornDate:DateTime
		/// </summary>	
		public DateTime? BornDate { get; set; }
                    
		/// <summary>
		/// Status:int
		/// </summary>	
		public int? Status { get; set; }
                    
		/// <summary>
		/// Pwd:string
		/// </summary>	
		public string Pwd { get; set; }
                    
		/// <summary>
		/// OpenId:string
		/// </summary>	
		public string OpenId { get; set; }
                    
		/// <summary>
		/// HeadIcon:string
		/// </summary>	
		public string HeadIcon { get; set; }
                    
		/// <summary>
		/// NikeName:string
		/// </summary>	
		public string NikeName { get; set; }
                    
		/// <summary>
		/// ProvinceId:string
		/// </summary>	
		public string ProvinceId { get; set; }
                    
		/// <summary>
		/// ProvinceName:string
		/// </summary>	
		public string ProvinceName { get; set; }
                    
		/// <summary>
		/// CityId:string
		/// </summary>	
		public string CityId { get; set; }
                    
		/// <summary>
		/// CityName:string
		/// </summary>	
		public string CityName { get; set; }
                    
		/// <summary>
		/// CountyId:string
		/// </summary>	
		public string CountyId { get; set; }
                    
		/// <summary>
		/// CountyName:string
		/// </summary>	
		public string CountyName { get; set; }
                    
		/// <summary>
		/// AddressInfo:string
		/// </summary>	
		public string AddressInfo { get; set; }
                    
		/// <summary>
		/// Money:decimal
		/// </summary>	
		public decimal? Money { get; set; }
                    
		/// <summary>
		/// Point:decimal
		/// </summary>	
		public decimal? Point { get; set; }
                    
		/// <summary>
		/// LevId:string
		/// </summary>	
		public string LevId { get; set; }
                    
		/// <summary>
		/// MemberNo:string
		/// </summary>	
		public string MemberNo { get; set; }
           
    }    
}
	