//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：MemberAddressEntity 
    /// </summary>
    [Serializable()]
    public partial class MemberAddressEntity:BaseModel
    {  
		            
		/// <summary>
		/// AddressId:string
		/// </summary>	
		public string AddressId { get; set; }
                    
		/// <summary>
		/// MemberId:string
		/// </summary>	
		public string MemberId { get; set; }
                    
		/// <summary>
		/// Consignee:string
		/// </summary>	
		public string Consignee { get; set; }
                    
		/// <summary>
		/// Mobile:string
		/// </summary>	
		public string Mobile { get; set; }
                    
		/// <summary>
		/// Address:string
		/// </summary>	
		public string Address { get; set; }
                    
		/// <summary>
		/// IsDefault:int
		/// </summary>	
		public int? IsDefault { get; set; }
                    
		/// <summary>
		/// ProvinceId:string
		/// </summary>	
		public string ProvinceId { get; set; }
                    
		/// <summary>
		/// ProvinceName:string
		/// </summary>	
		public string ProvinceName { get; set; }
                    
		/// <summary>
		/// CityId:string
		/// </summary>	
		public string CityId { get; set; }
                    
		/// <summary>
		/// CityName:string
		/// </summary>	
		public string CityName { get; set; }
                    
		/// <summary>
		/// CountyId:string
		/// </summary>	
		public string CountyId { get; set; }
                    
		/// <summary>
		/// CountyName:string
		/// </summary>	
		public string CountyName { get; set; }
           
    }    
}
	