//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：OrderEntity 
    /// </summary>
    [Serializable()]
    public partial class OrderEntity:BaseModel
    {  
		            
		/// <summary>
		/// OrderId:string
		/// </summary>	
		public string OrderId { get; set; }
                    
		/// <summary>
		/// BillCode:string
		/// </summary>	
		public string BillCode { get; set; }
                    
		/// <summary>
		/// OrderType:string
		/// </summary>	
		public string OrderType { get; set; }
                    
		/// <summary>
		/// OrderDate:DateTime
		/// </summary>	
		public DateTime? OrderDate { get; set; }
                    
		/// <summary>
		/// PayWay:int
		/// </summary>	
		public int? PayWay { get; set; }
                    
		/// <summary>
		/// ProCount:int
		/// </summary>	
		public int? ProCount { get; set; }
                    
		/// <summary>
		/// OrderMoney:decimal
		/// </summary>	
		public decimal? OrderMoney { get; set; }
                    
		/// <summary>
		/// OrderStatus:int
		/// </summary>	
		public int? OrderStatus { get; set; }
                    
		/// <summary>
		/// Remark:string
		/// </summary>	
		public string Remark { get; set; }
                    
		/// <summary>
		/// AddressId:string
		/// </summary>	
		public string AddressId { get; set; }
                    
		/// <summary>
		/// MemberMobile:string
		/// </summary>	
		public string MemberMobile { get; set; }
                    
		/// <summary>
		/// MemberName:string
		/// </summary>	
		public string MemberName { get; set; }
                    
		/// <summary>
		/// MemberNo:string
		/// </summary>	
		public string MemberNo { get; set; }
                    
		/// <summary>
		/// MemberId:string
		/// </summary>	
		public string MemberId { get; set; }
                    
		/// <summary>
		/// CreateDate:DateTime
		/// </summary>	
		public DateTime? CreateDate { get; set; }
                    
		/// <summary>
		/// ServiceTotal:decimal
		/// </summary>	
		public decimal? ServiceTotal { get; set; }
                    
		/// <summary>
		/// PayPoint:decimal
		/// </summary>	
		public decimal? PayPoint { get; set; }
           
    }    
}
	