//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：OrderDetailEntity 
    /// </summary>
    [Serializable()]
    public partial class OrderDetailEntity:BaseModel
    {  
		            
		/// <summary>
		/// OrderdetailId:string
		/// </summary>	
		public string OrderdetailId { get; set; }
                    
		/// <summary>
		/// ProductId:string
		/// </summary>	
		public string ProductId { get; set; }
                    
		/// <summary>
		/// Status:int
		/// </summary>	
		public int? Status { get; set; }
                    
		/// <summary>
		/// Price:decimal
		/// </summary>	
		public decimal? Price { get; set; }
                    
		/// <summary>
		/// OrderId:string
		/// </summary>	
		public string OrderId { get; set; }
                    
		/// <summary>
		/// BuyCount:string
		/// </summary>	
		public string BuyCount { get; set; }
                    
		/// <summary>
		/// ProductNo:string
		/// </summary>	
		public string ProductNo { get; set; }
                    
		/// <summary>
		/// ProductName:string
		/// </summary>	
		public string ProductName { get; set; }
                    
		/// <summary>
		/// ShipTempId:string
		/// </summary>	
		public string ShipTempId { get; set; }
                    
		/// <summary>
		/// FaceImag:string
		/// </summary>	
		public string FaceImag { get; set; }
                    
		/// <summary>
		/// YunFee:decimal
		/// </summary>	
		public decimal? YunFee { get; set; }
                    
		/// <summary>
		/// RuleName:string
		/// </summary>	
		public string RuleName { get; set; }
                    
		/// <summary>
		/// IsSq:bool
		/// </summary>	
		public bool? IsSq { get; set; }
                    
		/// <summary>
		/// RuleId:string
		/// </summary>	
		public string RuleId { get; set; }
                    
		/// <summary>
		/// ServiceRuleId:string
		/// </summary>	
		public string ServiceRuleId { get; set; }
                    
		/// <summary>
		/// ServicePrice:decimal
		/// </summary>	
		public decimal? ServicePrice { get; set; }
                    
		/// <summary>
		/// FreeServiceCount:decimal
		/// </summary>	
		public decimal? FreeServiceCount { get; set; }
                    
		/// <summary>
		/// ServiceTotal:decimal
		/// </summary>	
		public decimal? ServiceTotal { get; set; }
           
    }    
}
	