//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：ProductEntity 
    /// </summary>
    [Serializable()]
    public partial class ProductEntity:BaseModel
    {  
		            
		/// <summary>
		/// ProductId:string
		/// </summary>	
		public string ProductId { get; set; }
                    
		/// <summary>
		/// ProductNO:string
		/// </summary>	
		public string ProductNO { get; set; }
                    
		/// <summary>
		/// ProductUnit:string
		/// </summary>	
		public string ProductUnit { get; set; }
                    
		/// <summary>
		/// ProductDescription:string
		/// </summary>	
		public string ProductDescription { get; set; }
                    
		/// <summary>
		/// ProductStatus:int
		/// </summary>	
		public int? ProductStatus { get; set; }
                    
		/// <summary>
		/// ProductCategoryId:string
		/// </summary>	
		public string ProductCategoryId { get; set; }
                    
		/// <summary>
		/// ProductPrice:decimal
		/// </summary>	
		public decimal? ProductPrice { get; set; }
                    
		/// <summary>
		/// ProductCostPrice:decimal
		/// </summary>	
		public decimal? ProductCostPrice { get; set; }
                    
		/// <summary>
		/// ProductStock:int
		/// </summary>	
		public int? ProductStock { get; set; }
                    
		/// <summary>
		/// SaleCount:int
		/// </summary>	
		public int? SaleCount { get; set; }
                    
		/// <summary>
		/// FaceImag:string
		/// </summary>	
		public string FaceImag { get; set; }
                    
		/// <summary>
		/// ProductType:string
		/// </summary>	
		public string ProductType { get; set; }
                    
		/// <summary>
		/// ProductName:string
		/// </summary>	
		public string ProductName { get; set; }
                    
		/// <summary>
		/// CreateTime:DateTime
		/// </summary>	
		public DateTime? CreateTime { get; set; }
                    
		/// <summary>
		/// AuditStatus:int
		/// </summary>	
		public int? AuditStatus { get; set; }
                    
		/// <summary>
		/// Specifi:string
		/// </summary>	
		public string Specifi { get; set; }
                    
		/// <summary>
		/// ShipTempId:string
		/// </summary>	
		public string ShipTempId { get; set; }
                    
		/// <summary>
		/// ServiceRuleId:string
		/// </summary>	
		public string ServiceRuleId { get; set; }
           
    }    
}
	