//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：SalePlanEntity 
    /// </summary>
    [Serializable()]
    public partial class SalePlanEntity:BaseModel
    {  
		            
		/// <summary>
		/// SalePlanId:string
		/// </summary>	
		public string SalePlanId { get; set; }
                    
		/// <summary>
		/// PlanTitle:string
		/// </summary>	
		public string PlanTitle { get; set; }
                    
		/// <summary>
		/// SaleStartTime:DateTime
		/// </summary>	
		public DateTime? SaleStartTime { get; set; }
                    
		/// <summary>
		/// SaleEndTime:DateTime
		/// </summary>	
		public DateTime? SaleEndTime { get; set; }
                    
		/// <summary>
		/// Remark:string
		/// </summary>	
		public string Remark { get; set; }
                    
		/// <summary>
		/// PlanStatus:int
		/// </summary>	
		public int? PlanStatus { get; set; }
           
    }    
}
	