//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-06 10:09:18 by bruced
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
    
using System;
namespace Trade.Model
{
    /// <summary>
    /// 数据表实体类：ShipFeesEntity 
    /// </summary>
    [Serializable()]
    public partial class ShipFeesEntity:BaseModel
    {  
		            
		/// <summary>
		/// ShipFeesId:string
		/// </summary>	
		public string ShipFeesId { get; set; }
                    
		/// <summary>
		/// ShipTempId:string
		/// </summary>	
		public string ShipTempId { get; set; }
                    
		/// <summary>
		/// StartValue:decimal
		/// </summary>	
		public decimal StartValue { get; set; }
                    
		/// <summary>
		/// StartFee:decimal
		/// </summary>	
		public decimal StartFee { get; set; }
                    
		/// <summary>
		/// AddValue:decimal
		/// </summary>	
		public decimal AddValue { get; set; }
                    
		/// <summary>
		/// AddFee:decimal
		/// </summary>	
		public decimal AddFee { get; set; }
                    
		/// <summary>
		/// ProvinceId:string
		/// </summary>	
		public string ProvinceId { get; set; }
                    
		/// <summary>
		/// ProvinceName:string
		/// </summary>	
		public string ProvinceName { get; set; }
                    
		/// <summary>
		/// CityId:string
		/// </summary>	
		public string CityId { get; set; }
                    
		/// <summary>
		/// CityName:string
		/// </summary>	
		public string CityName { get; set; }
                    
		/// <summary>
		/// CountyId:string
		/// </summary>	
		public string CountyId { get; set; }
                    
		/// <summary>
		/// CountyName:string
		/// </summary>	
		public string CountyName { get; set; }
           
    }    
}
	